services:
  meshtastic-builder:
    build: .
    devices:
      - "${USB_DEVICE}:/dev/ttyUSB0"
    volumes:
      - "${MESHTASTIC_FIRMWARE_PATH}:/tmp/firmware"
    working_dir: /tmp/firmware
    stdin_open: true
    tty: true
    network_mode: bridge
    privileged: true