/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "spi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SpiPacket, SpiPacket, 2)


PB_BIND(SpiHeader, SpiHeader, AUTO)


PB_BIND(Request, Request, AUTO)


PB_BIND(Request_ConnectToNetwork, Request_ConnectToNetwork, AUTO)


PB_BIND(Response, Response, 2)


PB_BIND(Response_ConnectToNetwork, Response_ConnectToNetwork, AUTO)


PB_BIND(Response_LoRaMessageReceived, Response_LoRaMessageReceived, 2)


PB_BIND(Response_Status, Response_Status, AUTO)


PB_BIND(LoRaMessage, LoRaMessage, 2)


PB_BIND(LoRaModulationParams, LoRaModulationParams, AUTO)


PB_BIND(LoRaPacketParams, LoRaPacketParams, AUTO)










